language: python
python:
  - "3.6"
before_install:
- pip install poetry
install:
- poetry install
script: pytest --flake8 --cov=lstar --cov-report=html -n2
cache:
  directories:
    - ${HOME}/.cache/pip
after_success:
  - codecov
